// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alloptions.proto

package main

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/wyy-go/gogo-nrpc"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StringArg struct {
	Arg1                 string   `protobuf:"bytes,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArg) Reset()      { *m = StringArg{} }
func (*StringArg) ProtoMessage() {}
func (*StringArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea5e80d0b81a3163, []int{0}
}
func (m *StringArg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StringArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StringArg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StringArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArg.Merge(m, src)
}
func (m *StringArg) XXX_Size() int {
	return m.Size()
}
func (m *StringArg) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArg.DiscardUnknown(m)
}

var xxx_messageInfo_StringArg proto.InternalMessageInfo

func (m *StringArg) GetArg1() string {
	if m != nil {
		return m.Arg1
	}
	return ""
}

type SimpleStringReply struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleStringReply) Reset()      { *m = SimpleStringReply{} }
func (*SimpleStringReply) ProtoMessage() {}
func (*SimpleStringReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea5e80d0b81a3163, []int{1}
}
func (m *SimpleStringReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimpleStringReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimpleStringReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SimpleStringReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleStringReply.Merge(m, src)
}
func (m *SimpleStringReply) XXX_Size() int {
	return m.Size()
}
func (m *SimpleStringReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleStringReply.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleStringReply proto.InternalMessageInfo

func (m *SimpleStringReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*StringArg)(nil), "main.StringArg")
	proto.RegisterType((*SimpleStringReply)(nil), "main.SimpleStringReply")
}

func init() { proto.RegisterFile("alloptions.proto", fileDescriptor_ea5e80d0b81a3163) }

var fileDescriptor_ea5e80d0b81a3163 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0x41, 0x80, 0xe6, 0x41, 0xeb, 0x70, 0x45, 0xe0, 0x78, 0x38, 0x2a, 0x4f, 0x45, 0x42,
	0x96, 0x6a, 0x26, 0xc6, 0xd2, 0x01, 0x84, 0xe4, 0x0a, 0xc5, 0x12, 0x1d, 0x18, 0x22, 0xd7, 0x39,
	0x99, 0x43, 0xb6, 0xcf, 0x3d, 0xbf, 0x54, 0x62, 0x43, 0x1d, 0x3b, 0x75, 0xe4, 0x27, 0x30, 0x47,
	0xb2, 0xc4, 0xc0, 0x80, 0x98, 0x10, 0x13, 0x23, 0x63, 0xed, 0x85, 0x15, 0xa9, 0x0b, 0x23, 0xb2,
	0xcf, 0x84, 0x26, 0x52, 0x45, 0xa1, 0x93, 0x9f, 0xdf, 0xbd, 0xfb, 0xbe, 0xef, 0x7d, 0x9f, 0x0d,
	0xfd, 0x20, 0x8e, 0x65, 0x86, 0x42, 0xa6, 0xb9, 0x93, 0x29, 0x89, 0x92, 0x76, 0x93, 0x40, 0xa4,
	0x16, 0xa4, 0x2a, 0x0b, 0x75, 0xc7, 0x82, 0x48, 0x46, 0x52, 0xd7, 0xf6, 0x5d, 0xe8, 0xf9, 0xa8,
	0x44, 0x1a, 0x6d, 0xaa, 0x88, 0x52, 0xe8, 0x06, 0x2a, 0xda, 0x30, 0xc9, 0x1a, 0x59, 0xef, 0x0d,
	0x9b, 0xda, 0xbe, 0x07, 0x37, 0x7d, 0x91, 0x64, 0x31, 0xd7, 0x63, 0x43, 0x9e, 0xc5, 0xaf, 0xe9,
	0x2d, 0xb8, 0xa2, 0xea, 0xa2, 0x9d, 0xd4, 0x2f, 0xee, 0xf7, 0x4b, 0xd0, 0xf7, 0xf7, 0xc3, 0xad,
	0x49, 0x8e, 0x32, 0xf1, 0x27, 0xbb, 0xaf, 0x78, 0x88, 0x74, 0x1b, 0x96, 0x3d, 0xd4, 0x08, 0xfa,
	0xae, 0xe1, 0xd4, 0x82, 0x9c, 0x19, 0xab, 0x75, 0xa7, 0x6d, 0x2c, 0xb2, 0xd8, 0xab, 0x07, 0xd3,
	0x81, 0x91, 0xe0, 0x28, 0x6f, 0x4e, 0x46, 0x0d, 0x09, 0xbd, 0x0f, 0xd7, 0x3d, 0x7c, 0x2e, 0xc5,
	0xf8, 0x0c, 0x34, 0x70, 0x9a, 0x4d, 0xeb, 0x09, 0xbb, 0x43, 0x1f, 0xd6, 0xd3, 0xdb, 0x72, 0xc8,
	0xf7, 0x26, 0x3c, 0x47, 0x6a, 0xe8, 0xc3, 0x59, 0xe3, 0x6c, 0xee, 0x0e, 0xdd, 0x04, 0xc3, 0x43,
	0x1f, 0x15, 0x0f, 0x12, 0x3e, 0xfe, 0x57, 0xe9, 0xdd, 0xa3, 0xe9, 0x80, 0xd0, 0x2d, 0xb8, 0xfd,
	0x5b, 0xeb, 0xde, 0x3c, 0xd2, 0x29, 0x95, 0x7f, 0x01, 0xb1, 0xe8, 0xa7, 0x13, 0x73, 0x25, 0x6c,
	0x3c, 0x1d, 0xe5, 0xda, 0x54, 0xf7, 0x83, 0x76, 0xba, 0xf5, 0xf8, 0x59, 0xa0, 0x82, 0x24, 0xa7,
	0x4f, 0x61, 0xd5, 0xc3, 0x1d, 0x81, 0x2f, 0xe7, 0xdb, 0xe7, 0xa2, 0x5a, 0x39, 0x9c, 0x0e, 0x2e,
	0x27, 0xd9, 0x86, 0x7e, 0xb8, 0xf4, 0x05, 0xac, 0x2d, 0x2c, 0xff, 0x9f, 0xc0, 0x74, 0x1e, 0xb8,
	0xb1, 0x65, 0x1d, 0x7a, 0x3a, 0x94, 0x45, 0x27, 0x96, 0xff, 0xc4, 0xa3, 0x33, 0x78, 0x0c, 0xf4,
	0x54, 0x7c, 0x3b, 0x2d, 0xf1, 0xf9, 0x53, 0xbc, 0xd6, 0xb2, 0x5b, 0x37, 0xbe, 0x9c, 0x98, 0x4b,
	0x61, 0x2c, 0x78, 0x8a, 0x62, 0xec, 0x7a, 0xd0, 0x9f, 0x5d, 0xf6, 0xb9, 0xda, 0x17, 0x21, 0xbf,
	0xc0, 0x97, 0xf2, 0xe8, 0xc9, 0x41, 0x61, 0x76, 0x95, 0x94, 0x78, 0x58, 0x98, 0x4b, 0x22, 0xcd,
	0x31, 0x48, 0x43, 0x7e, 0x54, 0x98, 0xe4, 0x6d, 0x61, 0x92, 0x6f, 0x25, 0xeb, 0x1c, 0x97, 0x8c,
	0xfc, 0x28, 0x19, 0xf9, 0x59, 0x32, 0xf2, 0xa6, 0x62, 0xe4, 0x5d, 0xc5, 0xc8, 0xfb, 0x8a, 0x91,
	0x8f, 0x15, 0x23, 0x9f, 0x2b, 0x46, 0xbe, 0x56, 0x8c, 0x1c, 0x57, 0x8c, 0xec, 0x5e, 0x6d, 0x7e,
	0xca, 0x07, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x09, 0x6c, 0xaa, 0xc6, 0x03, 0x00, 0x00,
}

func (this *StringArg) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*StringArg)
	if !ok {
		that2, ok := that.(StringArg)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *StringArg")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *StringArg but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *StringArg but is not nil && this == nil")
	}
	if this.Arg1 != that1.Arg1 {
		return fmt.Errorf("Arg1 this(%v) Not Equal that(%v)", this.Arg1, that1.Arg1)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *StringArg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StringArg)
	if !ok {
		that2, ok := that.(StringArg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Arg1 != that1.Arg1 {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *SimpleStringReply) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SimpleStringReply)
	if !ok {
		that2, ok := that.(SimpleStringReply)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SimpleStringReply")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SimpleStringReply but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SimpleStringReply but is not nil && this == nil")
	}
	if this.Reply != that1.Reply {
		return fmt.Errorf("Reply this(%v) Not Equal that(%v)", this.Reply, that1.Reply)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *SimpleStringReply) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SimpleStringReply)
	if !ok {
		that2, ok := that.(SimpleStringReply)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Reply != that1.Reply {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *StringArg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&main.StringArg{")
	s = append(s, "Arg1: "+fmt.Sprintf("%#v", this.Arg1)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SimpleStringReply) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&main.SimpleStringReply{")
	s = append(s, "Reply: "+fmt.Sprintf("%#v", this.Reply)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAlloptions(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *StringArg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StringArg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StringArg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Arg1) > 0 {
		i -= len(m.Arg1)
		copy(dAtA[i:], m.Arg1)
		i = encodeVarintAlloptions(dAtA, i, uint64(len(m.Arg1)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SimpleStringReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimpleStringReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SimpleStringReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Reply) > 0 {
		i -= len(m.Reply)
		copy(dAtA[i:], m.Reply)
		i = encodeVarintAlloptions(dAtA, i, uint64(len(m.Reply)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAlloptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovAlloptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedStringArg(r randyAlloptions, easy bool) *StringArg {
	this := &StringArg{}
	this.Arg1 = string(randStringAlloptions(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedAlloptions(r, 2)
	}
	return this
}

func NewPopulatedSimpleStringReply(r randyAlloptions, easy bool) *SimpleStringReply {
	this := &SimpleStringReply{}
	this.Reply = string(randStringAlloptions(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedAlloptions(r, 2)
	}
	return this
}

type randyAlloptions interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneAlloptions(r randyAlloptions) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringAlloptions(r randyAlloptions) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneAlloptions(r)
	}
	return string(tmps)
}
func randUnrecognizedAlloptions(r randyAlloptions, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldAlloptions(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldAlloptions(dAtA []byte, r randyAlloptions, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateAlloptions(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateAlloptions(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateAlloptions(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateAlloptions(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateAlloptions(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateAlloptions(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateAlloptions(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *StringArg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Arg1)
	if l > 0 {
		n += 1 + l + sovAlloptions(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SimpleStringReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reply)
	if l > 0 {
		n += 1 + l + sovAlloptions(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAlloptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAlloptions(x uint64) (n int) {
	return sovAlloptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *StringArg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StringArg{`,
		`Arg1:` + fmt.Sprintf("%v", this.Arg1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SimpleStringReply) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SimpleStringReply{`,
		`Reply:` + fmt.Sprintf("%v", this.Reply) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAlloptions(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *StringArg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlloptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StringArg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StringArg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arg1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlloptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlloptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAlloptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arg1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlloptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAlloptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimpleStringReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAlloptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimpleStringReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimpleStringReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAlloptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAlloptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAlloptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAlloptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAlloptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAlloptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAlloptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAlloptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAlloptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAlloptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAlloptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAlloptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAlloptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAlloptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAlloptions = fmt.Errorf("proto: unexpected end of group")
)
